### ISSUE TITLE
current master not working - vagrant up fails

### ISSUE THREAD

**Issue by sbuerk** [Tuurlijk/TYPO3.Homestead#34]
Cloning the repo and startuing the machine with vagrant up fails.

Done this multiple time, with editiong Configuration/vagrant.yml and without.

```
sbuerk@sbhome /var/www/typo/box/typo-review $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'Michiel/Development'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'Michiel/Development' is up to date...
==> default: Setting the name of the VM: typo-review_default_1469907782261_33587
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (5.0.22) and guest (5.0.24) do not match.
Reading package lists...
Building dependency tree...
linux-headers-4.4.0-28-generic is already the newest version (4.4.0-28.47).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.0.22 - guest version is 5.0.24
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.0.22 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 5.0.24 of VirtualBox Guest Additions...
Removing existing VirtualBox non-DKMS kernel modules ...done.
update-initramfs: Generating /boot/initrd.img-/4.4.0-21-generic
update-initramfs: Generating /boot/initrd.img-/4.4.0-28-generic
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules
The make utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.

The gcc utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.

Building the main Guest Additions module ...fail!
(Look at /var/log/vboxadd-install.log to find out what went wrong)
Doing non-kernel setup of the Guest Additions ...done.
/etc/profile.d/phpbrew.sh: line 4: /home/vagrant/.phpbrew/bashrc: No such file or directory
vagrant_vbguest.machine_loop_guard
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:

Stderr from the command:

```

System

```
OS: Linux Mint 17.3 64Bit
Vagrant: 1.8.1
Virtualbox: 5.0.22 r108108 with 5.0.22 guest addiotons installed

```

Any idea or suggestion how to get this running ?

**Comment by Tuurlijk** [comment]
Hi Stefan,

Can you try to match the version of the installed guest box additions with the version of your virtualbox package?

Try upgrading virtualbox to 5.0.24. 

Maybe the upgrading of the guest additions should be optional. I think I will disable auto update. You can also disable it now in your Vagranfile as explained here: http://stackoverflow.com/questions/37556968/vagrant-disable-guest-additions

**Comment by Tuurlijk** [comment]
This should fix it: https://github.com/Tuurlijk/TYPO3.Homestead/commit/fa8e99d9a9b677f46bc700d3c426dd8d97c05553

**Comment by sbuerk** [comment]
Hi Michiel,

first of all, you have to look at your fix again, because it breaks now when no vagrant vbguest plugin is installed. See below.

Upgrading to virtualbox 5.0.24, GuestAddtions also and manuel adding the fix you have done did not solved the problem for me, yesterday. Strange. Done this after writing this issue.

So, because i have played a lot with many things in the last weeks i decieded to reinstall my whole system, done in the morning.

Just installed current releases for vagrant, virtualbox and cloned this repo.

You have to rework your fix .. because if the vbguest plugin is not installed, your fix will break this now

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'Michiel/Development' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'Michiel/Development'
    default: URL: https://atlas.hashicorp.com/Michiel/Development
==> default: Adding box 'Michiel/Development' (v0.3.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/Michiel/boxes/Development/versions/0.3.0/providers/virtualbox.box
==> default: Successfully added box 'Michiel/Development' (v0.3.0) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'vbguest'.
```

Commenting the config line out, everything was okay.

Afterwards i reinstalled the vbguest plugin , destroyed the box, reactivated your fix and run vagrant up again .. fix working for vbguest plugin installed now ( strange, maybe was to tiered done it manual yesterday )

Running vagrant up again, everthing was okay with your fix.

So, anyway , thanks a lot for the fast solution .. but breaking stuff for other is not good either ;)

**Comment by Tuurlijk** [comment]
Ok, I wrapped the setting with a `if Vagrant.has_plugin?("vagrant-vbguest")`. Hope that solves the config section error.
